/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Visao;

import Controle.CadHotelDAO;
import java.awt.Image;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Pichau
 */
public class FormFiltros extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormFiltros.class.getName());
    private CadHotelDAO h;
    private double minimo = 0;
    private double maximo = 0;
    private TelaPrincipal tela;
    /**
     * Creates new form FormFiltros
     */
    public FormFiltros(CadHotelDAO h, TelaPrincipal tela) {
        initComponents();
        Image image = new ImageIcon(getClass().getResource("/Imagens/icone.jpg")).getImage();
        this.setIconImage(image);
        this.setTitle("Filtros");
        this.h = h;
        this.tela = tela;
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         String[] estados = {
            "Selecione",
            "Acre",
            "Alagoas",
            "Amapá",
            "Amazonas",
            "Bahia",
            "Ceará",
            "Distrito Federal",
            "Espírito Santo",
            "Goiás",
            "Maranhão",
            "Mato Grosso",
            "Mato Grosso do Sul",
            "Minas Gerais",
            "Pará",
            "Paraíba",
            "Paraná",
            "Pernambuco",
            "Piauí",
            "Rio de Janeiro",
            "Rio Grande do Norte",
            "Rio Grande do Sul",
            "Rondônia",
            "Roraima",
            "Santa Catarina",
            "São Paulo",
            "Sergipe",
            "Tocantins"
        };
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(estados));
        precoMin.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                
                if(precoMin.getText().equals("Min.")) {
                    precoMin.setText("");
                }
            }
            
            @Override
            public void focusLost(FocusEvent e) {
                if(precoMin.getText().isEmpty()) {
                    precoMin.setText("Min.");
                }
            }
        });
        precoMax.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                
                if(precoMax.getText().equals("Max.")) {
                    precoMax.setText("");
                }
            }
            
            @Override
            public void focusLost(FocusEvent e) {
                if(precoMax.getText().isEmpty()) {
                    precoMax.setText("Max.");
                }
            }
        });
        this.setVisible(true);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        precoMin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        precoMax = new javax.swing.JTextField();
        aplicarFiltros = new javax.swing.JButton();
        btnLimparFiltros = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Fitlrar por estado:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Preço entre: ");

        precoMin.setText("Min.");
        precoMin.addActionListener(this::precoMinActionPerformed);

        jLabel3.setText("e");

        precoMax.setText("Max.");
        precoMax.addActionListener(this::precoMaxActionPerformed);

        aplicarFiltros.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        aplicarFiltros.setText("Aplicar Filtros");
        aplicarFiltros.addActionListener(this::aplicarFiltrosActionPerformed);

        btnLimparFiltros.setText("Limpar filtros");
        btnLimparFiltros.addActionListener(this::btnLimparFiltrosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(precoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(precoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aplicarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLimparFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(precoMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(precoMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(aplicarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimparFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private boolean verificarPrecos() {
        if(precoMin.getText().equals("Min.") || precoMax.getText().equals("Max.")) {
            return true;
        }
        try {
            String min = precoMin.getText();
            min = min.replace(",", ".");
            String max = precoMax.getText();
            max = max.replace(",", ".");
            
            minimo = Double.parseDouble(min);
            maximo = Double.parseDouble(max);
            
            if(minimo > maximo) {
                JOptionPane.showMessageDialog(null, "O minimo deve ser menor que o máximo");
            }
            if(minimo < 0) {
                JOptionPane.showMessageDialog(null, "O mínimo deve ser maior que zero");
            }
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Digite apenas números e vírgulas.");
            return false;
        }
        h.setPrecoMin(minimo);
        h.setPrecoMax(maximo);
        return true;
    }
    
    private void getFiltroEstado() {
        if(jComboBox1.getSelectedIndex() > 0) {
            h.setEstadoFiltro(jComboBox1.getSelectedItem().toString());
        }
    }
    
    private void limparFiltros() {
        minimo = 0;
        maximo = 0;
        h.setPrecoMin(minimo);
        h.setPrecoMax(maximo);
        jComboBox1.setSelectedIndex(0);
        h.setEstadoFiltro("");
    }
    
    private void precoMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoMaxActionPerformed

    private void aplicarFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aplicarFiltrosActionPerformed
        // TODO add your handling code here:
        verificarPrecos();
        getFiltroEstado();
        tela.mostrarHoteis();
        revalidate();
        repaint();
        this.dispose();
    }//GEN-LAST:event_aplicarFiltrosActionPerformed

    
    private void precoMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_precoMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_precoMinActionPerformed

    private void btnLimparFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparFiltrosActionPerformed
        // TODO add your handling code here:
        limparFiltros();
        tela.mostrarHoteis();
        revalidate();
        repaint();
        this.dispose();
    }//GEN-LAST:event_btnLimparFiltrosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aplicarFiltros;
    private javax.swing.JButton btnLimparFiltros;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField precoMax;
    private javax.swing.JTextField precoMin;
    // End of variables declaration//GEN-END:variables
}
