/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Visao;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Pichau
 */
public class MoldeImagem extends javax.swing.JPanel {

    /**
     * Creates new form MoldeImagem
     */
    private Image img;
    private int altura = 230;
    private int largura = 500;
    
    public MoldeImagem(){}
    
    public MoldeImagem(String caminho) {
        initComponents();
        this.setPreferredSize(new Dimension(largura, altura));
        this.setSize(largura, altura);
        this.img = new ImageIcon(caminho).getImage();
        this.setVisible(true);
        this.requestFocus();
        
    }
    
    public Image getImagem() {
        return this.img;
    }
    
    public void setImagem(String caminho) {
        this.img = new ImageIcon(caminho).getImage();
    }
    
    
    
    public void paintComponent(Graphics g) {
        super.paintComponent(g);
        if(img != null) {
            g.drawImage(img, 100, 10, largura, altura, null);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
