/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CadHotelDAO;
import Modelo.CadHotel;
import java.awt.FlowLayout;
import java.awt.GridLayout;

/**
 *
 * @author Vini G
 */
public class TelaPrincipal extends javax.swing.JFrame {

    CadHotelDAO hotelDAO = new CadHotelDAO();
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal(String usuario) {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabel2.setText("Entrou como: " + usuario);
        setLayout(new FlowLayout());
        PainelHoteis.setLayout(new GridLayout(hotelDAO.listarHoteis().size() / 3, 3, 5, 5));
        mostrarHoteis();
        setVisible(true);
    }
    
    private void mostrarHoteis() {
        for(CadHotel h : hotelDAO.listarHoteis()) {
            PainelHoteis.add(new TelaHoteis(h));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        PainelHoteis = new javax.swing.JPanel();
        btnTelaLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setText("Entrou como: ");

        javax.swing.GroupLayout PainelHoteisLayout = new javax.swing.GroupLayout(PainelHoteis);
        PainelHoteis.setLayout(PainelHoteisLayout);
        PainelHoteisLayout.setHorizontalGroup(
            PainelHoteisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );
        PainelHoteisLayout.setVerticalGroup(
            PainelHoteisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        btnTelaLogin.setText("Voltar para Login");
        btnTelaLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTelaLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(btnTelaLogin))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(PainelHoteis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(391, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(PainelHoteis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addComponent(btnTelaLogin)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTelaLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTelaLoginActionPerformed
        // TODO add your handling code here:
        String[] args = {};
        FormLogin.main(args);
        this.dispose();
    }//GEN-LAST:event_btnTelaLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelHoteis;
    private javax.swing.JButton btnTelaLogin;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    
    
}
